const ONE_SECOND = 1000;
const ONE_MINUTE = ONE_SECOND * 60;
const TRHEE_MINUTES = ONE_MINUTE * 3;
const FIVE_MINUTES = ONE_MINUTE * 5;

export { ONE_SECOND, ONE_MINUTE, TRHEE_MINUTES, FIVE_MINUTES };
